#
# Makefile for the rest of the USB drivers
# (the ones that don't fit into any other categories)
#
obj-$(CONFIG_USB_ADUTUX)		+= adutux.o
obj-$(CONFIG_USB_APPLEDISPLAY)		+= appledisplay.o
obj-$(CONFIG_USB_CYPRESS_CY7C63)	+= cypress_cy7c63.o
obj-$(CONFIG_USB_CYTHERM)		+= cytherm.o
obj-$(CONFIG_USB_EMI26)			+= emi26.o
obj-$(CONFIG_USB_EMI62)			+= emi62.o
obj-$(CONFIG_USB_EZUSB_FX2)		+= ezusb.o
obj-$(CONFIG_USB_FTDI_ELAN)		+= ftdi-elan.o
obj-$(CONFIG_USB_IDMOUSE)		+= idmouse.o
obj-$(CONFIG_USB_IOWARRIOR)		+= iowarrior.o
obj-$(CONFIG_USB_ISIGHTFW)		+= isight_firmware.o
obj-$(CONFIG_USB_LCD)			+= usblcd.o
obj-$(CONFIG_USB_LD)			+= ldusb.o
obj-$(CONFIG_USB_LED)			+= usbled.o
obj-$(CONFIG_USB_LEGOTOWER)		+= legousbtower.o
obj-$(CONFIG_USB_RIO500)		+= rio500.o
obj-$(CONFIG_USB_TEST)			+= usbtest.o
obj-$(CONFIG_USB_EHSET_TEST_FIXTURE)    += ehset.o
obj-$(CONFIG_USB_TRANCEVIBRATOR)	+= trancevibrator.o
obj-$(CONFIG_USB_USS720)		+= uss720.o
obj-$(CONFIG_USB_SEVSEG)		+= usbsevseg.o
obj-$(CONFIG_USB_YUREX)			+= yurex.o
obj-$(CONFIG_USB_HSIC_USB3503)		+= usb3503.o

obj-$(CONFIG_USB_SISUSBVGA)		+= sisusbvga/
obj-$(CONFIG_ANALOGIX_OHIO)             += anx7418/
obj-$(CONFIG_USB_LINK_LAYER_TEST)	+= lvstest.o
obj-$(CONFIG_USB_CCLOGIC_PI5USB)	+= pi5usb30216a.o
obj-$(CONFIG_USB_CCLOGIC_TUSB302L)	+= tusb302l.o
obj-$(CONFIG_USB_CYCCG)	        += cyccg.o
obj-$(CONFIG_USB_CCLOGIC_PTN5150)	+= ptn5150.o
obj-$(CONFIG_USB_CCLOGIC_PER30216)	+= pericom_i2c_30216c_v1.o
obj-$(CONFIG_USB_CCLOGIC_TUSB320)	+= tusb320.o
obj-y	                        += cclogic.o
