#obj-$(CONFIG_ANALOGIX_OHIO)	+= anx_ohio_driver.o anx_ohio_private_interface.o anx_ohio_public_interface.o
obj-$(CONFIG_ANALOGIX_OHIO)	+= ohio.o
ohio-objs := anx_ohio_driver.o anx_ohio_private_interface.o anx_ohio_public_interface.o
