#
# Makefile for the touchscreen drivers.
#


obj-$(CONFIG_TOUCHSCREEN_HIDEEP_TP_LETV)   += hideepm.o
hideepm-objs := hideep3d_core.o hideep_dbg.o hideep_isp.o hideep_isp_i2c.o hideep_sysfs.o hideep_procfs.o
